const primary = '#FF723F';
const accent = '#FF9A8F';

export const Colors = {
  light: {
    text: '#1A1A1A',
    background: '#FAFAFA',
    tint: primary,
    icon: '#737373',
    tabIconDefault: '#9B9B9B',
    tabIconSelected: primary,
    card: '#FFFFFF',
    border: '#E5E5E5',
    primary,
    primaryForeground: '#FFFFFF',
    secondary: '#F0F0F0',
    secondaryForeground: '#1A1A1A',
    muted: '#F5F5F5',
    mutedForeground: '#737373',
    accent,
    accentForeground: '#FFFFFF',
    destructive: '#EF4444',
    destructiveForeground: '#FFFFFF',
    success: '#16A34A',
    successForeground: '#FFFFFF',
    mapBackground: '#0F172A',
    shadow: 'rgba(17, 24, 39, 0.12)',
  },
  dark: {
    text: '#F5F5F5',
    background: '#0A0A0A',
    tint: primary,
    icon: '#888888',
    tabIconDefault: '#666666',
    tabIconSelected: primary,
    card: '#141414',
    border: '#262626',
    primary,
    primaryForeground: '#FFFFFF',
    secondary: '#1F1F1F',
    secondaryForeground: '#F5F5F5',
    muted: '#1A1A1A',
    mutedForeground: '#888888',
    accent,
    accentForeground: '#FFFFFF',
    destructive: '#DC2626',
    destructiveForeground: '#FFFFFF',
    success: '#22C55E',
    successForeground: '#0A0A0A',
    mapBackground: '#020617',
    shadow: 'rgba(0, 0, 0, 0.45)',
  },
};
